dist: xenial

matrix:
  include:
    - language: node_js
      node_js: "10"
      before_install:
        - cd web
      install:
        - npm install
      script:
        - npm run build

    - language: node_js
      node_js: "11"
      before_install:
        - cd web
      install:
        - npm install
      script:
        - npm run build

    - language: node_js
      node_js: "12"
      before_install:
        - cd web
      install:
        - npm install
      script:
        - npm run build

    - language: node_js
      node_js: "10"
      before_script:
        - mkdir meshcentral && cd meshcentral
      script:
        - npm install meshcentral

    - language: node_js
      node_js: "11"
      before_script:
        - mkdir meshcentral && cd meshcentral
      script:
        - npm install meshcentral

    - language: node_js
      node_js: "12"
      before_script:
        - mkdir meshcentral && cd meshcentral
      script:
        - npm install meshcentral

    - language: python
      python: "3.7"
      services:
        - postgresql

      before_script:
        - psql -c 'CREATE DATABASE travisci;' -U postgres
        - psql -c "CREATE USER travisci WITH PASSWORD 'travisSuperSekret6645';" -U postgres
        - psql -c 'GRANT ALL PRIVILEGES ON DATABASE travisci TO travisci;' -U postgres
        - psql -c 'ALTER USER travisci CREATEDB;' -U postgres

      before_install:
        - cd api/tacticalrmm

      install:
        - pip install --upgrade pip
        - pip install -r requirements.txt -r requirements-test.txt

      script:
        - python manage.py test -v 2

    - language: python
      python: "3.8"
      services:
        - postgresql

      before_script:
        - psql -c 'CREATE DATABASE travisci;' -U postgres
        - psql -c "CREATE USER travisci WITH PASSWORD 'travisSuperSekret6645';" -U postgres
        - psql -c 'GRANT ALL PRIVILEGES ON DATABASE travisci TO travisci;' -U postgres
        - psql -c 'ALTER USER travisci CREATEDB;' -U postgres

      before_install:
        - cd api/tacticalrmm

      install:
        - pip install --upgrade pip
        - pip install -r requirements.txt -r requirements-test.txt

      script:
        - python manage.py test -v 2
