trigger:
- develop


jobs:
- job: setup_env
  displayName: 'Setup Environment'
  strategy:
    matrix:
      Ubuntu18:
        AGENT_NAME: 'rmm-ubuntu18'
  
  pool:
    name: linux-vms
    demands:
      - agent.name -equals $(AGENT_NAME)
  
  steps:
    
  - script: |
      cd /home/steam/myagent/_work/1/s/api
      python3.7 -m venv env
      source env/bin/activate
      python --version
      deactivate
      python --version
    displayName: 'Run Tests'